docker-compose-yaml: docker-compose.yml

project: snipeit
endpoint: api-lagoon-master.lagoon.ch.amazee.io:31472
api: api-lagoon-master.lagoon.ch.amazee.io:80

tasks:
  post-rollout:
    - run:
        name: Create directories
        command: mkdir -p /app/storage/app/backups /app/storage/debugbar /app/storage/framework/cache /app/storage/framework/views /app/storage/framework/sessions /app/storage/private_uploads
        service: cli
#    - run:
#        name: Create symlinks
#        command: ln -sf /app/data/uploads /app/public && ln -sf /app/data/storage /app
#        service: cli
    - run:
        name: Run migrations
        command: php artisan migrate
        service: cli
    - run:
        name: Run storage link
        command: php artisan storage:link
        service: cli
#    - run:
#        name: Clear artisan
#        command: php artisan config:clear && php artisan view:clear && php artisan cache:clear && php artisan route:clear
#        service: cli
#    - run:
#        name: Clear cache
#        command: php artisan config:cache
#        service: cli

environments:
 prod:
   routes:
    - nginx:
       - "snipeit.amazeelabs.com"
   cronjobs:
     - name: artisan schedule
       schedule: "* * * * *"
       command: cd /app && php artisan schedule:run
       service: cli
 dev:
   routes:
      - nginx:
        - "snipeit-dev.ch.amazee.io"
