docker-compose-yaml: docker-compose.yml

project: snipeit
endpoint: api-lagoon-master.lagoon.ch.amazee.io:31472
api: api-lagoon-master.lagoon.ch.amazee.io:80

tasks:
  post-rollout:
#    - run:
#        name: Create directories
#        command: mkdir -p /app/storage/app/backups /app/storage/debugbar /app/storage/framework/cache /app/storage/framework/views /app/storage/framework/sessions /app/storage/private_uploads
#        service: cli
    - run:
        name: Run migrations
        command: php artisan migrate
        service: cli

environments:
 prod:
   routes:
    - nginx:
       - "snipeit.amazeelabs.com"
   cronjobs:
     - name: artisan schedule
       schedule: "* * * * *"
       command: cd /app && php artisan schedule:run
       service: cli
 dev:
   routes:
      - nginx:
        - "snipeit-dev.ch.amazee.io"
