docker-compose-yaml: docker-compose.yml

project: snipeit
endpoint: api-lagoon-master.lagoon.ch.amazee.io:31472
api: api-lagoon-master.lagoon.ch.amazee.io:80

tasks:
  post-rollout:
    - run:
        name: Run migrations
        command: php artisan migrate
        service: cli

environments:
 master:
   routes:
     - nginx:
       - "snipeit.amazeelabs.com"
