FROM amazeeio/php:7.3-cli
COPY lagoon/php-worker.ini /usr/local/etc/php/php.ini
COPY . /app

RUN apk add \
 openldap-dev \
 openldap  \
 libzip-dev \
 tar \
 unzip \
 && docker-php-ext-configure ldap --with-libdir=lib/ \
 && docker-php-ext-install ldap \
 && docker-php-ext-configure zip --with-libzip=/usr/include \
 && docker-php-ext-install zip

RUN composer install --no-dev --prefer-source

ENV WEBROOT=public
ENV PAGER=less
ENV PHP_MEMORY_LIMIT=8192M
CMD ["/app/scripts/worker.sh"]
