ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM amazeeio/nginx
COPY lagoon/nginx.conf /etc/nginx/conf.d/app.conf

COPY --from=cli /app /app

RUN php artisan storage:link

ENV WEBROOT=public

RUN ls  /etc/nginx/conf.d/
