
<?php
/**
 * This file is autogenerated by Laragoon
 */
return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('MARIADB_HOST', env('DB_HOST', 'snipe-it-dev.c8am9gyg9p6b.eu-central-1.rds.amazonaws.com')),
            'port' => env('MARIADB_PORT', env('DB_PORT', '3306')),
            'database' => env('MARIADB_DATABASE', env('DB_DATABASE', 'snipeit')),
            'username' => env('MARIADB_USERNAME', env('DB_USERNAME', 'admin')),
            'password' => env('MARIADB_PASSWORD', env('DB_PASSWORD', '18AX8E4u366F8Ez1')),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
    ],
    'migrations' => 'migrations',
    'redis' => [
        'client' => 'predis',
        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],
    ],
];
